"""add task template_id

Revision ID: aadbebe43c0c
Revises: 1f095c8381ae
Create Date: 2026-08-18 04:44:33.641994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aadbebe43c0c'
down_revision: Union[str, None] = '1f095c8381ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_review_task_template_id', 'format_template', ['template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_review_task_template_id', type_='foreignkey')
        batch_op.drop_column('template_id')

    # ### end Alembic commands ###
